# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=512, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=512, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u0414\u0435\u043d\u044c \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a',
                'verbose_name_plural': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438',
            },
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['email'], name='subscribes__email_943747_idx'),
        ),
    ]
